#!/system/bin/sh
export PATH=/system/bin:$PATH

mount -o rw,remount /system
mount -t rootfs -o remount,rw rootfs

cp -f /system/media/audio/ui/PowerOn.ogg.bak /system/media/audio/ui/PowerOn.ogg
cp -f /system/media/audio/ui/PowerOff.ogg.bak /system/media/audio/ui/PowerOff.ogg
cp -f /system/etc/PowerOn.ogg.bak /system/etc/PowerOn.ogg
cp -f /system/etc/PowerOff.ogg.bak /system/etc/PowerOff.ogg

rm -r /system/media/audio/ui/PowerOn.ogg.bak
rm -r /system/media/audio/ui/PowerOff.ogg.bak
rm -r /system/etc/PowerOn.ogg.bak
rm -r /system/etc/PowerOff.ogg.bak
